version: '2.1'

services:
  web:
    tty: true
    stdin_open: true
    depends_on:
      - 'mongo'
    image: samrose3/shrink-link
    build: .
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/shrink-link
    ports:
      - 3000:3000
    command: npm start
  mongo:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
volumes:
  mongo:
